export const reducerCases ={
    SET_AUDIO_CALL: "SET_AUDIO_CALL",
    SET_VIDEO_CALL: "SET_VIDEO_CALL",
    END_CALL:"END_CALL",
    SET_INCOMING_AUDIO_CALL: "SET_INCOMING_AUDIO_CALL",
    SET_INCOMING_VIDEO_CALL:"SET_INCOMING_VIDEO_CALL",
};